--- 
cache: 
  directories: 
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
deploy: 
  api_key: $GITHUB_TOKEN
  file: 
    - "dist_electron/Vusic 0.1.0.AppImage"
    - dist_electron/vusic_0.1.0_amd64.deb
    - dist_electron/Vusic-0.1.0.dmg
    - "dist_electron\\Vusic Setup 0.1.0.exe"
  provider: releases
  skip_cleanup: true
install: "npm i"
matrix: 
  include: 
    - 
      env: 
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      language: node_js
      node_js: "10"
      os: osx
      osx_image: xcode9.4
    - 
      language: generic
      os: linux
    - 
      language: node_js
      node_js: "10"
      os: windows
script: 
  - "npm run build"
