name: Release

# Inspiration
# https://github.com/actions/create-release/issues/14

# FIXME Make file names consistent??
# - "dist_electron/DAWG 0.1.1.AppImage"
# - "dist_electron/vusic_0.1.1_amd64.deb"
# - "dist_electron/vusic_0.1.1.rpm"
# - "dist_electron/DAWG-0.1.1.dmg"
# - "dist_electron\\DAWG Setup 0.1.1.exe"

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Removing "refs/tags/v"
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # Note that v is prepended because it is removed above
          name: v${{ steps.get_version.outputs.VERSION }}
          body_path: changelogs/${{ steps.get_version.outputs.VERSION }}-CHANGELOG.md
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          # OK so I don't think we can set draft to true or else the build can't upload artifacts
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output Release Version File
        run: echo "${{ steps.get_version.outputs.VERSION }}" > release_version.txt
      - name: Save Version File for publish
        uses: actions/upload-artifact@v1
        with:
          name: release_version
          path: release_version.txt

  build:
    name: Build
    needs: [release]
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load Version
        uses: actions/download-artifact@v1
        with:
          name: release_version

      - uses: pCYSl5EDgo/cat@master
        id: get_version
        with:
          path: release_version/release_version.txt

      - name: Information Output
        id: information_output
        run: echo Version -> ${{ steps.get_version.outputs.text }}

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # Necessary because there is a currently a dependency audio-decode > av > speaker which fails to be built on windows
      # *But* it is an optional depedency so we don't actually need to install thankfully
      - run: npm ci --no-optional
      - run: npm run install-app-deps

      # https://github.com/electron-userland/electron-builder/issues/4176
      - name: Temporarily fix electron-builder (Windows, Linux)
        if: matrix.os != 'macos-latest'
        run: |
          sed -i 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash

      - name: Temporarily fix electron-builder (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          sed -i '' 's/\^\[\\w/\^\[.\\w/g' node_modules/builder-util/out/util.js
        shell: bash

      - run: npm run build
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: v${{ steps.get_version.outputs.text }}
          files: 'dist_electron/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
